puzzle_states = {
    0: 'OFF',
    1: 'ON',
    2: 'ACTIVE',
    3: 'STANDBY',
    4: 'SOLVED',
    5: 'OFFLINE',
    6: 'FAILURE',
    7: 'SYSTEM_ERROR',
    8: 'ERROR',
    9: 'SYNCRONIZED',
    10: 'INITIALIZING',
    11: 'INITIALIZED',
    12: 'START',
    13: 'END',
    14: 'READING',
    15: 'PLAYING',
    16: 'BALANCED',
    17: 'SETUP',
    18: 'FLASH',
    19: 'UNBALANCED',
    20: 'ALARM',
    21: 'RESET',
    22: 'UNSOLVED',
    23: 'DONE',
    24: 'DISABLE',
    25: 'ENABLE',
    26: 'PAUSE',
    27: 'COUNTING',
    28: 'START_TIMER',
    29: 'CHARGING',
    30: 'FULL',
    31: 'EMPTY',
    32: 'OPEN',
    33: 'CLOSED',
    34: 'NODATA',
    35: 'TRANSMITTED',
    36: 'KEY_ENTERED',
    37: 'DETECTED',
    38: 'OUT_OF_RANGE'
}

puzzle_registers_meta = {
    "power_control": {
        0: "master force",
        1: "master command",
        2: "master body",
        3: "slave millis",
        4: "slave confirm",
        5: "slave state",
        6: "power adjuster state",
        7: "battery state",
        8: "power light indicator state",
        9: "speaker state",
        10: "light effect state",
        11: "battery",
        12: "slave supply",
        13: "slave demand",
        14: "slave light effect pattern number",
        15: "slave battery max value",
        16: "slave battery charging rate",
        17: "slave failure period value",
        18: "---",
        19: "---",
        20: "---",
    },
    "status_board": {
        0: "master force",
        1: "master command",
        2: "master body",
        3: "slave millis",
        4: "slave confirm",
        5: "slave state",
        6: "game power switch state",
        7: "ship prep status state",
        8: "life support status state",
        9: "laser grid status state",
        10: "blast door status state",
        11: "countdown state",
        12: "countdown value",
        13: "countdown",
        14: "speaker state",
        15: "---",
        16: "---",
        17: "---",
        18: "---",
        19: "---",
        20: "---",
    },
    "datamatic": {
        0: "master force",
        1: "master command",
        2: "master body",
        3: "slave millis",
        4: "slave confirm",
        5: "slave state",
        6: "power switch state",
        7: "code reader state",
        8: "information display state",
        9: "light effect state",
        10: "speaker state",
        11: "---",
        12: "---",
        13: "---",
        14: "---",
        15: "---",
        16: "---",
        17: "---",
        18: "---",
        19: "---",
        20: "---",
    },
    "safeomatic": {
        0: "master force",
        1: "master command",
        2: "master body",
        3: "slave millis",
        4: "slave confirm",
        5: "slave state",
        6: "power switch state",
        7: "access panel state",
        8: "combination reader state",
        9: "door state",
        10: "speaker state",
        11: "---",
        12: "---",
        13: "---",
        14: "---",
        15: "---",
        16: "---",
        17: "---",
        18: "---",
        19: "---",
        20: "---",
    },
    "life_support": {
        0: "master force",
        1: "master command",
        2: "master body",
        3: "slave millis",
        4: "slave confirm",
        5: "slave state",
        6: "power switch state",
        7: "air pressure status state",
        8: "air supply pump state",
        9: "external vent state",
        10: "light effect state",
        11: "speaker state",
        12: "light effect pattern number",
        13: "air pressure status value",
        14: "---",
        15: "---",
        16: "---",
        17: "---",
        18: "---",
        19: "---",
        20: "---",
    },
    "docked_ship": {
        0: "master force",
        1: "master ship prep command",
        2: "master ship prep body",
        3: "slave ship prep millis",
        4: "slave ship prep confirm",
        5: "slave ship prep state",
        6: "ship prep power switch state",
        7: "ship prep battery matrix state",
        8: "ship prep generator state",
        9: "ship prep speaker state",
        10: "energy supplemental command ",
        11: "energy supplemental body",
        12: "energy supplemental millis",
        13: "energy supplemental confirm",
        14: "energy supplemental state",
        15: "energy supplemental power switch state",
        16: "energy supplemental power adjuster state",
        17: "energy supplemental synco reader state",
        18: "energy supplemental speaker state",
        19: "energy supplemental syncro reader imput key",
        20: "---",
    },
    "prep_status": {
        0: "master force",
        1: "master command",
        2: "master body",
        3: "slave millis",
        4: "slave confirm",
        5: "slave state",
        6: "power switch state",
        7: "battery matrix state",
        8: "energy supp state",
        9: "generator state",
        10: "synchro reader state",
        11: "speaker state",
        12: "light effect state",
        13: "synchro reader input key",
        14: "light effect pattern number",
        15: "---",
        16: "---",
        17: "---",
        18: "---",
        19: "---",
        20: "---",
    },
    "lasergrid": {
        0: "master force",
        1: "master command",
        2: "master body",
        3: "slave millis",
        4: "slave confirm",
        5: "slave state",
        6: "power switch state",
        7: "key reader state",
        8: "wave adjuster state",
        9: "speaker state",
        10: "---",
        11: "---",
        12: "---",
        13: "---",
        14: "---",
        15: "---",
        16: "---",
        17: "---",
        18: "---",
        19: "---",
        20: "---",
    },
    "keypad": {
        0: "master force",
        1: "master command",
        2: "master body",
        3: "slave millis",
        4: "slave confirm",
        5: "slave state",
        6: "code reader state",
        7: "speaker state",
        8: "slave key",
        9: "---",
        10: "---",
        11: "---",
        12: "---",
        13: "---",
        14: "---",
        15: "---",
        16: "---",
        17: "---",
        18: "---",
        19: "---",
        20: "---",
    },
    "laserbar": {
        0: "master force",
        1: "master command",
        2: "master body",
        3: "slave millis",
        4: "slave confirm",
        5: "slave state",
        6: "detector state",
        7: "speaker state",
        8: "---",
        9: "---",
        10: "---",
        11: "---",
        12: "---",
        13: "---",
        14: "---",
        15: "---",
        16: "---",
        17: "---",
        18: "---",
        19: "---",
        20: "---",
    }
}