from enum import Enum
class STATE(Enum):
    
  OFF = 0
  ON = 1
  ACTIVE = 2
  STANDBY = 3
  SOLVED = 4
  OFFLINE = 5
  FAILURE = 6
  SYSTEM_ERROR = 7
  ERROR = 8
  SYNCRONIZED = 9
  INITIALIZING = 10
  INITIALIZED = 11
  START = 12
  END = 13
  READING = 14
  PLAYING = 15
  BALANCED = 16
  SETUP = 17
  FLASH = 18
  UNBALANCED = 19
  ALARM = 20
  RESET = 21
  UNSOLVED = 22
  DONE = 23
  DISABLE = 24
  ENABLE = 25
  PAUSE = 26
  RESET = 27
  NODATA = 38

class COMMAND(Enum):
    CMD_NONE = 0
    CMD_ENABLE = 1
    CMD_DISABLE = 2
    CMD_RESET = 3
    CMD_PAUSE = 4
    CMD_SET_DEMAND = 5

class REGISTER_INDEX(Enum):
    REG_MASTER_MILLIS = 0
    REG_MASTER_COMMAND = 1
    REG_MASTER_FORCE = 2
    REG_SLAVE_MILLIS = 3
    REG_SLAVE_CONFIRM = 4
    REG_SLAVE_STATE = 5

class DATAMATIC_REGISTER_INDEX(REGISTER_INDEX):
    REG_SLAVE_POWER_SWITCH_STATE = 6
    REG_SLAVE_CODE_READER_STATE = 7
    REG_SLAVE_INFORMATION_DISPLAY_STATE = 8
    REG_SLAVE_LIGHT_EFFECT_STATE = 9
    REG_SLAVE_SPEAKER_STATE = 10

class PC_REGISTER_INDEX(REGISTER_INDEX):
    REG_SLAVE_POWER_ADJUSTER_STATE = 6,
    REG_SLAVE_BATTERY_STATE = 7,
    REG_SLAVE_POWER_LIGHT_INDICATOR_STATE = 8,
    REG_SLAVE_SPEAKER_STATE = 9,
    REG_SLAVE_LIGHT_EFFECT_STATE = 10,
    REG_SLAVE_BATTERY = 11,
    REG_SLAVE_SUPPLY = 12,
    REG_SLAVE_DEMAND = 13,
    REG_SLAVE_LIGHT_EFFECT_PATTERN_NUMBER = 14